---
config:
  layout: elk
  look: handDrawn
  theme: dark
---
block
    columns 3
    
    client["Whatsappp app"]
    
    space
    block:server:3
        columns 1
        block
            columns 7
            apigateway["API gateway"]
            space
            loadbalancer["Load balancer"]
            space
            chatservice["Chat service"]
            space
            notficationservice["Notification Service"]
        end

        space
        
        kafka["Kafka"]
        
        space

        database[("Database")]
    end
    space:3
    
    space:2
    pushserver["Android push notification server"]

    client-->apigateway
    apigateway-->loadbalancer
    loadbalancer-->chatservice
    chatservice-->kafka
    chatservice-->database
    kafka-->notficationservice
    notficationservice-->pushserver
    notficationservice-- "Websocket" -->client
    pushserver -- "Push notification" -->client
